spring:
  application:
    name: everhaven-be
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/everhavenv1db
    username: root
    password: 114514
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          autocommit: false
  sql:
    init:
      mode: always
      encoding: UTF-8

app:
  image:
    local-dir: uploads/images
    public-prefix: /media
    sync-on-startup: true
    public-base-url: http://localhost:8080
  ai:
    api-key: "ms-7a4f6a60-5ea7-4a11-844d-627cac18a983"
    base-url: "https://api-inference.modelscope.cn/v1"
    model: "Qwen/Qwen3.5-27B"

management:
  endpoints:
    web:
      exposure:
        include: health,info
        exclude: env,beans

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.cyf.everhavenbe: DEBUG
    org.springframework.web: DEBUG
    # 显示 SQL 语句 (Hibernate)
    org.hibernate.SQL: DEBUG
    # 显示 SQL 绑定参数 (Hibernate)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # 显示 MyBatis Plus 相关执行日志
    com.cyf.everhavenbe.mapper: TRACE
    com.baomidou.mybatisplus: DEBUG

#debug: true
