CREATE TABLE IF NOT EXISTS carousel_slides (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    image VARCHAR(500) NOT NULL,
    image_dark VARCHAR(500) NULL,
    type VARCHAR(50) DEFAULT 'hero',
    title VARCHAR(200) NOT NULL,
    subtitle VARCHAR(500),
    `link` VARCHAR(500),
    `label` VARCHAR(100),
    description VARCHAR(1000),
    sort_order INT DEFAULT 0,
    status BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE carousel_slides ADD COLUMN IF NOT EXISTS image_dark VARCHAR(500) NULL AFTER image;
ALTER TABLE carousel_slides ADD COLUMN IF NOT EXISTS `link` VARCHAR(500) NULL AFTER subtitle;
ALTER TABLE carousel_slides ADD COLUMN IF NOT EXISTS `label` VARCHAR(100) NULL AFTER `link`;
ALTER TABLE carousel_slides ADD COLUMN IF NOT EXISTS description VARCHAR(1000) NULL AFTER `label`;

